# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.     # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: joel@spacetraders.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from spacetraders-sdk import schemas  # noqa: F401


class ShipType(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    
    @schemas.classproperty
    def PROBE(cls):
        return cls("SHIP_PROBE")
    
    @schemas.classproperty
    def MINING_DRONE(cls):
        return cls("SHIP_MINING_DRONE")
    
    @schemas.classproperty
    def INTERCEPTOR(cls):
        return cls("SHIP_INTERCEPTOR")
    
    @schemas.classproperty
    def LIGHT_HAULER(cls):
        return cls("SHIP_LIGHT_HAULER")
    
    @schemas.classproperty
    def COMMAND_FRIGATE(cls):
        return cls("SHIP_COMMAND_FRIGATE")
    
    @schemas.classproperty
    def EXPLORER(cls):
        return cls("SHIP_EXPLORER")
    
    @schemas.classproperty
    def HEAVY_FREIGHTER(cls):
        return cls("SHIP_HEAVY_FREIGHTER")
    
    @schemas.classproperty
    def LIGHT_SHUTTLE(cls):
        return cls("SHIP_LIGHT_SHUTTLE")
    
    @schemas.classproperty
    def ORE_HOUND(cls):
        return cls("SHIP_ORE_HOUND")
    
    @schemas.classproperty
    def REFINING_FREIGHTER(cls):
        return cls("SHIP_REFINING_FREIGHTER")
