# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.     # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: joel@spacetraders.io
    Generated by: https://openapi-generator.tech
"""

from spacetraders.paths.my_ships_ship_symbol_chart.post import CreateChart
from spacetraders.paths.my_ships_ship_symbol_scan_ships.post import CreateShipShipScan
from spacetraders.paths.my_ships_ship_symbol_scan_systems.post import CreateShipSystemScan
from spacetraders.paths.my_ships_ship_symbol_scan_waypoints.post import CreateShipWaypointScan
from spacetraders.paths.my_ships_ship_symbol_survey.post import CreateSurvey
from spacetraders.paths.my_ships_ship_symbol_dock.post import DockShip
from spacetraders.paths.my_ships_ship_symbol_extract.post import ExtractResources
from spacetraders.paths.my_ships_ship_symbol.get import GetMyShip
from spacetraders.paths.my_ships_ship_symbol_cargo.get import GetMyShipCargo
from spacetraders.paths.my_ships.get import GetMyShips
from spacetraders.paths.my_ships_ship_symbol_cooldown.get import GetShipCooldown
from spacetraders.paths.my_ships_ship_symbol_nav.get import GetShipNav
from spacetraders.paths.my_ships_ship_symbol_jettison.post import Jettison
from spacetraders.paths.my_ships_ship_symbol_jump.post import JumpShip
from spacetraders.paths.my_ships_ship_symbol_navigate.post import NavigateShip
from spacetraders.paths.my_ships_ship_symbol_negotiate_contract.post import NegotiateContract
from spacetraders.paths.my_ships_ship_symbol_orbit.post import OrbitShip
from spacetraders.paths.my_ships_ship_symbol_nav.patch import PatchShipNav
from spacetraders.paths.my_ships_ship_symbol_purchase.post import PurchaseCargo
from spacetraders.paths.my_ships.post import PurchaseShip
from spacetraders.paths.my_ships_ship_symbol_refuel.post import RefuelShip
from spacetraders.paths.my_ships_ship_symbol_sell.post import SellCargo
from spacetraders.paths.my_ships_ship_symbol_refine.post import ShipRefine
from spacetraders.paths.my_ships_ship_symbol_transfer.post import TransferCargo
from spacetraders.paths.my_ships_ship_symbol_warp.post import WarpShip


class FleetApi(
    CreateChart,
    CreateShipShipScan,
    CreateShipSystemScan,
    CreateShipWaypointScan,
    CreateSurvey,
    DockShip,
    ExtractResources,
    GetMyShip,
    GetMyShipCargo,
    GetMyShips,
    GetShipCooldown,
    GetShipNav,
    Jettison,
    JumpShip,
    NavigateShip,
    NegotiateContract,
    OrbitShip,
    PatchShipNav,
    PurchaseCargo,
    PurchaseShip,
    RefuelShip,
    SellCargo,
    ShipRefine,
    TransferCargo,
    WarpShip,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
